// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDqZMj5nFcRyFPZnl2RzcglMCup_NfuigE',
    appId: '1:523211182868:web:687fc18fb15cf91cd26801',
    messagingSenderId: '523211182868',
    projectId: 'idapp-34577',
    authDomain: 'idapp-34577.firebaseapp.com',
    storageBucket: 'idapp-34577.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC-1KxTFklJLh_GRxMjVV2Bf8HMf_hnwZc',
    appId: '1:523211182868:android:fdedf697d0ef8668d26801',
    messagingSenderId: '523211182868',
    projectId: 'idapp-34577',
    storageBucket: 'idapp-34577.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDw4z2B69q8XdW3clYEaiAKSYHthIY4Kb4',
    appId: '1:523211182868:ios:a0fb3339be7ddba5d26801',
    messagingSenderId: '523211182868',
    projectId: 'idapp-34577',
    storageBucket: 'idapp-34577.appspot.com',
    iosBundleId: 'com.example.idApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDw4z2B69q8XdW3clYEaiAKSYHthIY4Kb4',
    appId: '1:523211182868:ios:e085a576a40cc3e5d26801',
    messagingSenderId: '523211182868',
    projectId: 'idapp-34577',
    storageBucket: 'idapp-34577.appspot.com',
    iosBundleId: 'com.example.idApp.RunnerTests',
  );
}
